version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ai_bot
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: