version: '3.9'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--dns-result-order=ipv4first
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 1.0.0.1
    dns_search: []
    restart: unless-stopped
    volumes:
      - ./assets:/app/assets
    networks:
      - app-network
    extra_hosts:
      - "api.telegram.org:149.154.167.220"

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ai_bot
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16